spring.application.name=clinical-service
server.port=8083

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=clinical_db
spring.data.mongodb.username=root
spring.data.mongodb.password=rootpassword
spring.data.mongodb.authentication-database=admin

api.security.token.secret=12345678-conecta-saude-secret-key

identity.service.url=http://localhost:8083
appointment.service.url=http://localhost:8081